version: '3.8'

services:
  ubuntu-node:
    build: ./ubuntu
    container_name: ubuntu-node
    ports:
      - "2222:22"              # SSH access
      - "9100:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  ubuntu-node2: 
    build: ./ubuntu 
    container_name: ubuntu-node2 
    ports: 
      - "3333:22"              # SSH access 
      - "9102:9100"            # Node exporter port 
    networks: 
      - monitor-net 
    tty: true 

  ubuntu-node3: 
    build: ./ubuntu 
    container_name: ubuntu-node3
    ports: 
      - "4444:22"              # SSH access 
      - "9103:9100"            # Node exporter port 
    networks: 
      - monitor-net 
    tty: true 

  ubuntu-node4:
    build: ./ubuntu
    container_name: ubuntu-node4
    ports:
      - "5555:22"              # SSH access
      - "9104:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  ubuntu-node5:
    build: ./ubuntu
    container_name: ubuntu-node5
    ports:
      - "6666:22"              # SSH access
      - "9105:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  ubuntu-node6:
    build: ./ubuntu
    container_name: ubuntu-node6
    ports:
      - "7777:22"              # SSH access
      - "9106:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  ubuntu-node7:
    build: ./ubuntu
    container_name: ubuntu-node7
    ports:
      - "8888:22"              # SSH access
      - "9107:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  ubuntu-node8:
    build: ./ubuntu
    container_name: ubuntu-node8
    ports:
      - "9999:22"              # SSH access
      - "9108:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  ubuntu-node9:
    build: ./ubuntu
    container_name: ubuntu-node9
    ports:
      - "11111:22"             # SSH access
      - "9109:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  ubuntu-node10:
    build: ./ubuntu
    container_name: ubuntu-node10
    ports:
      - "11112:22"             # SSH access
      - "9110:9100"            # Node exporter port
    networks:
      - monitor-net
    tty: true

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/simple-dashboard.json:/var/lib/grafana/simple-dashboard.json

networks:
  monitor-net:
    driver: bridge

